application: APP_ID
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.2"

handlers:
- url: /
  script: main.app

- url: /publish
  script: publish.app

- url: /subscribe
  script: subscribe.app

