window['PubSub'] = function () {

  var token;
  var APP_ID = 'pubsubchannel';

  function S4() {
           return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
     }

  function guid() {
             return (S4() + S4() + S4() + S4() + S4() + S4() + S4() + S4());
  }

  var clientId = guid();

  function id() {
	  return clientId;
  }

  function subscribe(group, callback) {
      $.getJSON('http://' + APP_ID + '.appspot.com/subscribe?group=' + group + "&client=" + clientId + "&callback=?", function(result) {
			   token = result.token;
			   channel = new goog.appengine.Channel(result.token);
			   socket = channel.open()
			   socket.onmessage = function (data) {
				    var message = decodeURIComponent(data.data) 
                                    var json = JSON.parse(message);
				    callback(json);
			   };
               });
  }

  function publish(group,json) {
   $.ajax({url:'http://' + APP_ID + '.appspot.com/publish?group=' + group + "&token=" + token,
	   data: JSON.stringify(json),
           type: "POST",
           beforeSend: function(xhr) {
	      xhr.setRequestHeader('Content-Type','application/json');
	   }});
  }

  return {'id':id,
	  'subscribe': subscribe,
	  'publish': publish };

}();

(function() { var h,l=this,m=function(a,b,c){a=a.split(".");c=c||l;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]?c[d]:c[d]={}:c[d]=b},aa=function(a,b){for(var c=a.split("."),d=b||l,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d},ba=function(){},ca=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";
if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},p=function(a){return void 0!==a},q=function(a){return"array"==ca(a)},da=function(a){var b=
ca(a);return"array"==b||"object"==b&&"number"==typeof a.length},s=function(a){return"string"==typeof a},t=function(a){return"function"==ca(a)},ea=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ha=function(a){return a[fa]||(a[fa]=++ga)},fa="closure_uid_"+(1E9*Math.random()>>>0),ga=0,ia=function(a,b,c){return a.call.apply(a.bind,arguments)},ja=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);
Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},u=function(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return u.apply(null,arguments)},ka=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},v=Date.now||function(){return+new Date},w=function(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;
a.prototype=new c;a.yd=function(a,c,f){var g=Array.prototype.slice.call(arguments,2);return b.prototype[c].apply(a,g)}};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return u.apply(null,c)}return u(this,a)};var x=function(a){Error.captureStackTrace?Error.captureStackTrace(this,x):this.stack=Error().stack||"";a&&(this.message=String(a))};w(x,Error);x.prototype.name="CustomError";var la;var ma=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")},ua=function(a){if(!na.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(oa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(qa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ra,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(sa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(ta,"&#39;"));return a},oa=/&/g,qa=/</g,ra=/>/g,sa=/"/g,ta=/'/g,na=/[&<>"']/,va=function(a,
b){return a<b?-1:a>b?1:0};var wa=function(a,b){b.unshift(a);x.call(this,ma.apply(null,b));b.shift()};w(wa,x);wa.prototype.name="AssertionError";var y=function(a,b,c){if(!a){var d=Array.prototype.slice.call(arguments,2),e="Assertion failed";if(b)var e=e+(": "+b),f=d;throw new wa(""+e,f||[]);}},xa=function(a,b){throw new wa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var z=Array.prototype,ya=z.indexOf?function(a,b,c){y(null!=a.length);return z.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(s(a))return s(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},za=z.forEach?function(a,b,c){y(null!=a.length);z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=s(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Aa=z.filter?function(a,b,c){y(null!=a.length);return z.filter.call(a,
b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=s(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var n=g[k];b.call(c,n,k,a)&&(e[f++]=n)}return e},Ba=z.some?function(a,b,c){y(null!=a.length);return z.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=s(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},Ca=function(a,b){var c=ya(a,b),d;if(d=0<=c)y(null!=a.length),z.splice.call(a,c,1);return d},Da=function(a){return z.concat.apply(z,arguments)},Ea=function(a){var b=a.length;
if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Fa=function(a,b,c){y(null!=a.length);return 2>=arguments.length?z.slice.call(a,b):z.slice.call(a,b,c)};var Ga,Ha,Ia,Ja,Ka=function(){return l.navigator?l.navigator.userAgent:null};Ja=Ia=Ha=Ga=!1;var La;if(La=Ka()){var Ma=l.navigator;Ga=0==La.lastIndexOf("Opera",0);Ha=!Ga&&(-1!=La.indexOf("MSIE")||-1!=La.indexOf("Trident"));Ia=!Ga&&-1!=La.indexOf("WebKit");Ja=!Ga&&!Ia&&!Ha&&"Gecko"==Ma.product}var Na=Ga,A=Ha,C=Ja,D=Ia,Oa=function(){var a=l.document;return a?a.documentMode:void 0},Pa;
t:{var Qa="",Ra;if(Na&&l.opera)var Sa=l.opera.version,Qa="function"==typeof Sa?Sa():Sa;else if(C?Ra=/rv\:([^\);]+)(\)|;)/:A?Ra=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:D&&(Ra=/WebKit\/(\S+)/),Ra)var Ta=Ra.exec(Ka()),Qa=Ta?Ta[1]:"";if(A){var Ua=Oa();if(Ua>parseFloat(Qa)){Pa=String(Ua);break t}}Pa=Qa}
var Va=Pa,Wa={},E=function(a){var b;if(!(b=Wa[a])){b=0;for(var c=String(Va).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",n=RegExp("(\\d*)(\\D*)","g"),r=RegExp("(\\d*)(\\D*)","g");do{var B=n.exec(g)||["","",""],pa=r.exec(k)||["","",""];if(0==B[0].length&&0==pa[0].length)break;b=va(0==B[1].length?0:parseInt(B[1],10),0==pa[1].length?0:parseInt(pa[1],10))||va(0==B[2].length,
0==pa[2].length)||va(B[2],pa[2])}while(0==b)}b=Wa[a]=0<=b}return b},Xa=l.document,Ya=Xa&&A?Oa()||("CSS1Compat"==Xa.compatMode?parseInt(Va,10):5):void 0;var Za=null,$a=null,ab=null;var bb=function(){};var cb=function(a,b,c){this.B=a;this.lb=c||16;this.Bc=Array(this.lb);this.Ob=Array(this.lb);a=b;a.length>this.lb&&(this.B.update(a),a=this.B.Ga());for(c=0;c<this.lb;c++)b=c<a.length?a[c]:0,this.Bc[c]=b^92,this.Ob[c]=b^54;this.B.update(this.Ob)};w(cb,bb);cb.prototype.reset=function(){this.B.reset();this.B.update(this.Ob)};cb.prototype.update=function(a,b){this.B.update(a,b)};cb.prototype.Ga=function(){var a=this.B.Ga();this.B.reset();this.B.update(this.Bc);this.B.update(a);return this.B.Ga()};var db=function(){this.i=[];this.Jb=[];this.jd=[];this.jb=[];this.jb[0]=128;for(var a=1;64>a;++a)this.jb[a]=0;this.reset()};w(db,bb);db.prototype.reset=function(){this.i[0]=1732584193;this.i[1]=4023233417;this.i[2]=2562383102;this.i[3]=271733878;this.i[4]=3285377520;this.Mb=this.Ha=0};
var eb=function(a,b,c){c||(c=0);var d=a.jd;if(s(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.i[0];c=a.i[1];for(var g=a.i[2],k=a.i[3],n=a.i[4],r,e=0;80>e;e++)40>e?20>e?(f=k^c&(g^k),r=1518500249):(f=c^g^k,r=1859775393):60>e?(f=c&g|k&(c|g),r=2400959708):(f=c^g^k,r=3395469782),
f=(b<<5|b>>>27)+f+n+r+d[e]&4294967295,n=k,k=g,g=(c<<30|c>>>2)&4294967295,c=b,b=f;a.i[0]=a.i[0]+b&4294967295;a.i[1]=a.i[1]+c&4294967295;a.i[2]=a.i[2]+g&4294967295;a.i[3]=a.i[3]+k&4294967295;a.i[4]=a.i[4]+n&4294967295};
db.prototype.update=function(a,b){p(b)||(b=a.length);for(var c=b-64,d=0,e=this.Jb,f=this.Ha;d<b;){if(0==f)for(;d<=c;)eb(this,a,d),d+=64;if(s(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,64==f){eb(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,64==f){eb(this,e);f=0;break}}this.Ha=f;this.Mb+=b};
db.prototype.Ga=function(){var a=[],b=8*this.Mb;56>this.Ha?this.update(this.jb,56-this.Ha):this.update(this.jb,64-(this.Ha-56));for(var c=63;56<=c;c--)this.Jb[c]=b&255,b/=256;eb(this,this.Jb);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.i[c]>>d&255,++b;return a};var fb=function(a,b){for(var c in a)b.call(void 0,a[c],c,a)},gb=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},hb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},ib="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),jb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ib.length;f++)c=ib[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var kb=!A||A&&9<=Ya,lb=!C&&!A||A&&A&&9<=Ya||C&&E("1.9.1");A&&E("9");var mb=function(a,b){var c;c=a.className;c=s(c)&&c.match(/\S+/g)||[];for(var d=Fa(arguments,1),e=c.length+d.length,f=c,g=0;g<d.length;g++)0<=ya(f,d[g])||f.push(d[g]);a.className=c.join(" ");return c.length==e};var F=function(a){return a?new nb(9==a.nodeType?a:a.ownerDocument||a.document):la||(la=new nb)},pb=function(a,b){fb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in ob?a.setAttribute(ob[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},ob={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",
usemap:"useMap",valign:"vAlign",width:"width"},rb=function(a,b,c){function d(c){c&&b.appendChild(s(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!da(f)||ea(f)&&0<f.nodeType?d(f):za(qb(f)?Ea(f):f,d)}},sb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null},qb=function(a){if(a&&"number"==typeof a.length){if(ea(a))return"function"==typeof a.item||"string"==typeof a.item;if(t(a))return"function"==typeof a.item}return!1},nb=function(a){this.$=a||l.document||document},
tb=function(a,b){var c;c=a.$;var d=b&&"*"!=b?b.toUpperCase():"";c=c.querySelectorAll&&c.querySelector&&d?c.querySelectorAll(d+""):c.getElementsByTagName(d||"*");return c};h=nb.prototype;
h.xc=function(a,b,c){var d=this.$,e=arguments,f=e[0],g=e[1];if(!kb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',ua(g.name),'"');if(g.type){f.push(' type="',ua(g.type),'"');var k={};jb(k,g);delete k.type;g=k}f.push(">");f=f.join("")}f=d.createElement(f);g&&(s(g)?f.className=g:q(g)?mb.apply(null,[f].concat(g)):pb(f,g));2<e.length&&rb(d,f,e);return f};h.createElement=function(a){return this.$.createElement(a)};h.createTextNode=function(a){return this.$.createTextNode(String(a))};
h.e=function(){var a=this.$;return a.parentWindow||a.defaultView};h.appendChild=function(a,b){a.appendChild(b)};h.removeNode=sb;h.Ec=function(a){return lb&&void 0!=a.children?a.children:Aa(a.childNodes,function(a){return 1==a.nodeType})};var G=function(){};G.prototype.fa=!1;G.prototype.Sb=function(){this.fa||(this.fa=!0,this.f())};var ub=function(a,b){a.Ka||(a.Ka=[]);a.Ka.push(u(b,void 0))};G.prototype.f=function(){if(this.Ka)for(;this.Ka.length;)this.Ka.shift()()};var H=function(a){a&&"function"==typeof a.Sb&&a.Sb()};var I=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.va=!1;this.uc=!0};I.prototype.f=function(){};I.prototype.Sb=function(){};I.prototype.preventDefault=function(){this.defaultPrevented=!0;this.uc=!1};var vb=function(a){vb[" "](a);return a};vb[" "]=ba;var wb=function(a,b){try{return vb(a[b]),!0}catch(c){}return!1};var xb=!A||A&&9<=Ya,yb=A&&!E("9");!D||E("528");C&&E("1.9b")||A&&E("8")||Na&&E("9.5")||D&&E("528");C&&!E("8")||A&&E("9");var zb=function(a,b){I.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.kb=this.state=null;if(a){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?C&&(wb(d,"nodeName")||(d=null)):"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);
this.relatedTarget=d;this.offsetX=D||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=D||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.kb=
a;a.defaultPrevented&&this.preventDefault()}};w(zb,I);zb.prototype.preventDefault=function(){zb.w.preventDefault.call(this);var a=this.kb;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,yb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};zb.prototype.f=function(){};var Ab="closure_listenable_"+(1E6*Math.random()|0),Bb=function(a){try{return!(!a||!a[Ab])}catch(b){return!1}},Cb=0;var Db=function(a,b,c,d,e){this.da=a;this.hb=null;this.src=b;this.type=c;this.capture=!!d;this.fb=e;this.key=++Cb;this.sa=this.eb=!1},Eb=function(a){a.sa=!0;a.da=null;a.hb=null;a.src=null;a.fb=null};var Fb=function(a){this.src=a;this.t={};this.Fa=0};Fb.prototype.add=function(a,b,c,d,e){var f=this.t[a];f||(f=this.t[a]=[],this.Fa++);var g=Gb(f,b,d,e);-1<g?(a=f[g],c||(a.eb=!1)):(a=new Db(b,this.src,a,!!d,e),a.eb=c,f.push(a));return a};Fb.prototype.remove=function(a,b,c,d){if(!(a in this.t))return!1;var e=this.t[a];b=Gb(e,b,c,d);return-1<b?(Eb(e[b]),y(null!=e.length),z.splice.call(e,b,1),0==e.length&&(delete this.t[a],this.Fa--),!0):!1};
var Hb=function(a,b){var c=b.type;if(!(c in a.t))return!1;var d=Ca(a.t[c],b);d&&(Eb(b),0==a.t[c].length&&(delete a.t[c],a.Fa--));return d};Fb.prototype.$a=function(a){var b=0,c;for(c in this.t)if(!a||c==a){for(var d=this.t[c],e=0;e<d.length;e++)++b,Eb(d[e]);delete this.t[c];this.Fa--}return b};Fb.prototype.Ja=function(a,b,c,d){a=this.t[a];var e=-1;a&&(e=Gb(a,b,c,d));return-1<e?a[e]:null};var Gb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.sa&&f.da==b&&f.capture==!!c&&f.fb==d)return e}return-1};var Ib="closure_lm_"+(1E6*Math.random()|0),Jb={},Kb=0,Lb=function(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)Lb(a,b[f],c,d,e);return null}c=Mb(c);return Bb(a)?a.Ma(b,c,d,e):Nb(a,b,c,!1,d,e)},Nb=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=!!e,k=Ob(a);k||(a[Ib]=k=new Fb(a));c=k.add(b,c,d,e,f);if(c.hb)return c;d=Pb();c.hb=d;d.src=a;d.da=c;a.addEventListener?a.addEventListener(b,d,g):a.attachEvent(b in Jb?Jb[b]:Jb[b]="on"+b,d);Kb++;return c},Pb=function(){var a=Qb,b=xb?function(c){return a.call(b.src,
b.da,c)}:function(c){c=a.call(b.src,b.da,c);if(!c)return c};return b},Rb=function(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)Rb(a,b[f],c,d,e);return null}c=Mb(c);return Bb(a)?a.Pc(b,c,d,e):Nb(a,b,c,!0,d,e)},Sb=function(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)Sb(a,b[f],c,d,e);else c=Mb(c),Bb(a)?a.Nb(b,c,d,e):a&&(a=Ob(a))&&(b=a.Ja(b,c,!!d,e))&&Tb(b)},Tb=function(a){if("number"==typeof a||!a||a.sa)return!1;var b=a.src;if(Bb(b))return Hb(b.S,a);var c=a.type,d=a.hb;b.removeEventListener?b.removeEventListener(c,
d,a.capture):b.detachEvent&&b.detachEvent(c in Jb?Jb[c]:Jb[c]="on"+c,d);Kb--;(c=Ob(b))?(Hb(c,a),0==c.Fa&&(c.src=null,b[Ib]=null)):Eb(a);return!0},Ub=function(a,b,c,d,e){c=Mb(c);d=!!d;return Bb(a)?a.Ja(b,c,d,e):a?(a=Ob(a))?a.Ja(b,c,d,e):null:null},Wb=function(a,b,c,d){var e=1;if(a=Ob(a))if(b=a.t[b])for(b=Ea(b),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.sa&&(e&=!1!==Vb(f,d))}return Boolean(e)},Vb=function(a,b){var c=a.da,d=a.fb||a.src;a.eb&&Tb(a);return c.call(d,b)},Qb=function(a,b){if(a.sa)return!0;
if(!xb){var c=b||aa("window.event"),d=new zb(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){t:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.va&&0<=k;k--)d.currentTarget=c[k],e&=Wb(c[k],f,!0,d);for(k=0;!d.va&&k<c.length;k++)d.currentTarget=c[k],e&=Wb(c[k],f,!1,d)}return e}return Vb(a,new zb(b,this))},Ob=function(a){a=a[Ib];return a instanceof
Fb?a:null},Xb="__closure_events_fn_"+(1E9*Math.random()>>>0),Mb=function(a){y(a,"Listener can not be null.");if(t(a))return a;y(a.handleEvent,"An object listener must have handleEvent method.");return a[Xb]||(a[Xb]=function(b){return a.handleEvent(b)})};var Yb=function(){this.S=new Fb(this);this.md=this};w(Yb,G);Yb.prototype[Ab]=!0;h=Yb.prototype;h.Hb=null;h.addEventListener=function(a,b,c,d){Lb(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){Sb(this,a,b,c,d)};
h.dispatchEvent=function(a){Zb(this);var b,c=this.Hb;if(c){b=[];for(var d=1;c;c=c.Hb)b.push(c),y(1E3>++d,"infinite loop")}c=this.md;d=a.type||a;if(s(a))a=new I(a,c);else if(a instanceof I)a.target=a.target||c;else{var e=a;a=new I(d,c);jb(a,e)}var e=!0,f;if(b)for(var g=b.length-1;!a.va&&0<=g;g--)f=a.currentTarget=b[g],e=$b(f,d,!0,a)&&e;a.va||(f=a.currentTarget=c,e=$b(f,d,!0,a)&&e,a.va||(e=$b(f,d,!1,a)&&e));if(b)for(g=0;!a.va&&g<b.length;g++)f=a.currentTarget=b[g],e=$b(f,d,!1,a)&&e;return e};
h.f=function(){Yb.w.f.call(this);this.S&&this.S.$a(void 0);this.Hb=null};h.Ma=function(a,b,c,d){Zb(this);return this.S.add(String(a),b,!1,c,d)};h.Pc=function(a,b,c,d){return this.S.add(String(a),b,!0,c,d)};h.Nb=function(a,b,c,d){return this.S.remove(String(a),b,c,d)};var $b=function(a,b,c,d){b=a.S.t[String(b)];if(!b)return!0;b=Ea(b);for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.sa&&g.capture==c){var k=g.da,n=g.fb||g.src;g.eb&&Hb(a.S,g);e=!1!==k.call(n,d)&&e}}return e&&!1!=d.uc};
Yb.prototype.Ja=function(a,b,c,d){return this.S.Ja(String(a),b,c,d)};var Zb=function(a){y(a.S,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var ac=function(a,b){Yb.call(this);this.ta=a||1;this.ra=b||l;this.Kb=u(this.ld,this);this.Lb=v()};w(ac,Yb);h=ac.prototype;h.enabled=!1;h.F=null;h.ld=function(){if(this.enabled){var a=v()-this.Lb;0<a&&a<0.8*this.ta?this.F=this.ra.setTimeout(this.Kb,this.ta-a):(this.F&&(this.ra.clearTimeout(this.F),this.F=null),this.dispatchEvent("tick"),this.enabled&&(this.F=this.ra.setTimeout(this.Kb,this.ta),this.Lb=v()))}};
h.start=function(){this.enabled=!0;this.F||(this.F=this.ra.setTimeout(this.Kb,this.ta),this.Lb=v())};h.stop=function(){this.enabled=!1;this.F&&(this.ra.clearTimeout(this.F),this.F=null)};h.f=function(){ac.w.f.call(this);this.stop();delete this.ra};var bc=function(a,b){if(!t(a))if(a&&"function"==typeof a.handleEvent)a=u(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<b?-1:l.setTimeout(a,b||0)};var cc=function(a,b,c){this.Fb=a;this.ta=b||0;this.pa=c;this.hd=u(this.nd,this)};w(cc,G);h=cc.prototype;h.Y=0;h.f=function(){cc.w.f.call(this);this.stop();delete this.Fb;delete this.pa};h.start=function(a){this.stop();this.Y=bc(this.hd,p(a)?a:this.ta)};h.stop=function(){0!=this.Y&&l.clearTimeout(this.Y);this.Y=0};h.nd=function(){this.Y=0;this.Fb&&this.Fb.call(this.pa)};var J=function(a){this.pa=a;this.g={}};w(J,G);var dc=[];J.prototype.Ma=function(a,b,c,d){q(b)||(dc[0]=b,b=dc);for(var e=0;e<b.length;e++){var f=Lb(a,b[e],c||this.handleEvent,d||!1,this.pa||this);if(!f)break;this.g[f.key]=f}return this};J.prototype.Pc=function(a,b,c,d){return ec(this,a,b,c,d)};var ec=function(a,b,c,d,e,f){if(q(c))for(var g=0;g<c.length;g++)ec(a,b,c[g],d,e,f);else{b=Rb(b,c,d||a.handleEvent,e,f||a.pa||a);if(!b)return a;a.g[b.key]=b}return a};
J.prototype.Nb=function(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)this.Nb(a,b[f],c,d,e);else if(a=Ub(a,b,c||this.handleEvent,d,e||this.pa||this))Tb(a),delete this.g[a.key];return this};J.prototype.$a=function(){fb(this.g,Tb);this.g={}};J.prototype.f=function(){J.w.f.call(this);this.$a()};J.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var fc=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},ic=function(a){var b=[];gc(new hc,a,b);return b.join("")},hc=function(){this.ob=void 0},gc=function(a,b,c){switch(typeof b){case "string":jc(b,c);
break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(q(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],gc(a,a.ob?a.ob.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),jc(f,c),c.push(":"),gc(a,a.ob?a.ob.call(b,f,e):e,c),d=","));c.push("}");
break;case "function":break;default:throw Error("Unknown type: "+typeof b);}},kc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},lc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,jc=function(a,b){b.push('"',a.replace(lc,function(a){if(a in kc)return kc[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return kc[a]=e+b.toString(16)}),'"')};var mc="StopIteration"in l?l.StopIteration:Error("StopIteration"),nc=function(){};nc.prototype.next=function(){throw mc;};nc.prototype.td=function(){return this};var K=function(a,b){this.T={};this.g=[];this.ab=this.l=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof K?(c=a.oa(),d=a.X()):(c=hb(a),d=gb(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};K.prototype.X=function(){oc(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.T[this.g[b]]);return a};K.prototype.oa=function(){oc(this);return this.g.concat()};
K.prototype.Ea=function(a){return pc(this.T,a)};K.prototype.remove=function(a){return pc(this.T,a)?(delete this.T[a],this.l--,this.ab++,this.g.length>2*this.l&&oc(this),!0):!1};var oc=function(a){if(a.l!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];pc(a.T,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.l!=a.g.length){for(var e={},c=b=0;b<a.g.length;)d=a.g[b],pc(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}};K.prototype.get=function(a,b){return pc(this.T,a)?this.T[a]:b};
K.prototype.set=function(a,b){pc(this.T,a)||(this.l++,this.g.push(a),this.ab++);this.T[a]=b};K.prototype.Wa=function(){return new K(this)};K.prototype.td=function(a){oc(this);var b=0,c=this.g,d=this.T,e=this.ab,f=this,g=new nc;g.next=function(){for(;;){if(e!=f.ab)throw Error("The map has changed since the iterator was created");if(b>=c.length)throw mc;var g=c[b++];return a?g:d[g]}};return g};var pc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var qc=function(a){if("function"==typeof a.X)return a.X();if(s(a))return a.split("");if(da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return gb(a)},rc=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(da(a)||s(a))za(a,b,c);else{var d;if("function"==typeof a.oa)d=a.oa();else if("function"!=typeof a.X)if(da(a)||s(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=hb(a);else d=void 0;for(var e=qc(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};var tc=function(a){return sc(a||arguments.callee.caller,[])},sc=function(a,b){var c=[];if(0<=ya(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(uc(a)+"(");for(var d=a.arguments,e=0;e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=uc(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");
c.push(f)}b.push(a);c.push(")\n");try{c.push(sc(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")},uc=function(a){if(vc[a])return vc[a];a=String(a);if(!vc[a]){var b=/function ([^\(]+)/.exec(a);vc[a]=b?b[1]:"[Anonymous]"}return vc[a]},vc={};var wc=function(a,b,c,d,e){this.reset(a,b,c,d,e)};wc.prototype.ib=0;wc.prototype.Dc=null;wc.prototype.Cc=null;var xc=0;wc.prototype.reset=function(a,b,c,d,e){this.ib="number"==typeof e?e:xc++;d||v();this.Ia=a;this.kd=b;delete this.Dc;delete this.Cc};wc.prototype.Fc=function(a){this.Ia=a};var L=function(a){this.Mc=a};L.prototype.k=null;L.prototype.Ia=null;L.prototype.Rb=null;L.prototype.Nc=null;var yc=function(a,b){this.name=a;this.value=b};yc.prototype.toString=function(){return this.name};var zc=new yc("SEVERE",1E3),Ac=new yc("WARNING",900),Bc=new yc("INFO",800),Cc=new yc("CONFIG",700),Dc=new yc("FINE",500),Ec=new yc("FINEST",300);L.prototype.getName=function(){return this.Mc};L.prototype.getParent=function(){return this.k};L.prototype.Ec=function(){this.Rb||(this.Rb={});return this.Rb};
L.prototype.Fc=function(a){this.Ia=a};var Fc=function(a){if(a.Ia)return a.Ia;if(a.k)return Fc(a.k);xa("Root logger has no level set.");return null};L.prototype.log=function(a,b,c){if(a.value>=Fc(this).value)for(t(b)&&(b=b()),a=this.rd(a,b,c),b="log:"+a.kd,l.console&&(l.console.timeStamp?l.console.timeStamp(b):l.console.markTimeline&&l.console.markTimeline(b)),l.msWriteProfilerMark&&l.msWriteProfilerMark(b),b=this;b;){c=b;var d=a;if(c.Nc)for(var e=0,f=void 0;f=c.Nc[e];e++)f(d);b=b.getParent()}};
L.prototype.rd=function(a,b,c){var d=new wc(a,String(b),this.Mc);if(c){d.Dc=c;var e;var f=arguments.callee.caller;try{var g;var k=aa("window.location.href");if(s(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:k,stack:"Not available"};else{var n,r,B=!1;try{n=c.lineNumber||c.zd||"Not available"}catch(pa){n="Not available",B=!0}try{r=c.fileName||c.filename||c.sourceURL||l.$googDebugFname||k}catch(Te){r="Not available",B=!0}g=!B&&c.lineNumber&&c.fileName&&c.stack&&c.message&&
c.name?c:{message:c.message||"Not available",name:c.name||"UnknownError",lineNumber:n,fileName:r,stack:c.stack||"Not available"}}e="Message: "+ua(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+ua(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+ua(tc(f)+"-> ")}catch(pe){e="Exception trying to expose exception! You win, we lose. "+pe}d.Cc=e}return d};L.prototype.info=function(a,b){this.log(Bc,a,b)};
var Gc={},Hc=null,Ic=function(a){Hc||(Hc=new L(""),Gc[""]=Hc,Hc.Fc(Cc));var b;if(!(b=Gc[a])){b=new L(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Ic(a.substr(0,c));c.Ec()[d]=b;b.k=c;Gc[a]=b}return b};var N=function(a){var b=M;b&&b.log(Ec,a,void 0)},O=function(a,b){var c=M;c&&c.log(zc,a,b)},P=function(a,b,c){a&&a.log(Ac,b,c)},Q=function(a){var b=M;b&&b.info(a,void 0)},R=function(a){var b=M;b&&b.log(Dc,a,void 0)};var Jc=function(){this.Pa={}};w(Jc,G);Jc.prototype.tb=Ic("goog.messaging.AbstractChannel");Jc.prototype.O=function(a){a&&a()};Jc.prototype.C=function(){return!0};var Kc=function(a,b,c){a.Pa[b]={v:c,cc:!1}};Jc.prototype.f=function(){Jc.w.f.call(this);delete this.tb;delete this.Pa;delete this.Xb};var Lc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Nc=function(a){if(Mc){Mc=!1;var b=l.location;if(b){var c=b.href;if(c&&(c=(c=Nc(c)[3]||null)&&decodeURIComponent(c))&&c!=b.hostname)throw Mc=!0,Error();}}return a.match(Lc)},Mc=D,Oc=function(a){var b=Nc(a);a=b[1];var c=b[2],d=b[3],b=b[4],e="";a&&(e+=a+":");d&&(e+="//",c&&(e+=c+"@"),e+=d,b&&(e+=":"+b));return e};var S=function(a,b){var c;if(a instanceof S)this.G=p(b)?b:a.G,Pc(this,a.L),c=a.cb,T(this),this.cb=c,Qc(this,a.Da),Rc(this,a.qa),Sc(this,a.Gb),Tc(this,a.W.Wa()),c=a.bb,T(this),this.bb=c;else if(a&&(c=Nc(String(a)))){this.G=!!b;Pc(this,c[1]||"",!0);var d=c[2]||"";T(this);this.cb=d?decodeURIComponent(d):"";Qc(this,c[3]||"",!0);Rc(this,c[4]);Sc(this,c[5]||"",!0);Tc(this,c[6]||"",!0);c=c[7]||"";T(this);this.bb=c?decodeURIComponent(c):""}else this.G=!!b,this.W=new Uc(null,0,this.G)};h=S.prototype;h.L="";
h.cb="";h.Da="";h.qa=null;h.Gb="";h.bb="";h.wd=!1;h.G=!1;h.toString=function(){var a=[],b=this.L;b&&a.push(Vc(b,Wc),":");if(b=this.Da){a.push("//");var c=this.cb;c&&a.push(Vc(c,Wc),"@");a.push(encodeURIComponent(String(b)));b=this.qa;null!=b&&a.push(":",String(b))}if(b=this.Gb)this.Da&&"/"!=b.charAt(0)&&a.push("/"),a.push(Vc(b,"/"==b.charAt(0)?Xc:Yc));(b=this.W.toString())&&a.push("?",b);(b=this.bb)&&a.push("#",Vc(b,Zc));return a.join("")};h.Wa=function(){return new S(this)};
var Pc=function(a,b,c){T(a);a.L=c?b?decodeURIComponent(b):"":b;a.L&&(a.L=a.L.replace(/:$/,""))},Qc=function(a,b,c){T(a);a.Da=c?b?decodeURIComponent(b):"":b},Rc=function(a,b){T(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.qa=b}else a.qa=null},Sc=function(a,b,c){T(a);a.Gb=c?b?decodeURIComponent(b):"":b},Tc=function(a,b,c){T(a);b instanceof Uc?(a.W=b,a.W.Pb(a.G)):(c||(b=Vc(b,$c)),a.W=new Uc(b,0,a.G))},T=function(a){if(a.wd)throw Error("Tried to modify a read-only Uri");};
S.prototype.Pb=function(a){this.G=a;this.W&&this.W.Pb(a);return this};
var Vc=function(a,b){return s(a)?encodeURI(a).replace(b,ad):null},ad=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Wc=/[#\/\?@]/g,Yc=/[\#\?:]/g,Xc=/[\#\?]/g,$c=/[\#\?@]/g,Zc=/#/g,Uc=function(a,b,c){this.H=a||null;this.G=!!c},cd=function(a){if(!a.h&&(a.h=new K,a.l=0,a.H))for(var b=a.H.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=bd(a,e);
a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}};h=Uc.prototype;h.h=null;h.l=null;h.add=function(a,b){cd(this);this.H=null;a=bd(this,a);var c=this.h.get(a);c||this.h.set(a,c=[]);c.push(b);this.l++;return this};h.remove=function(a){cd(this);a=bd(this,a);return this.h.Ea(a)?(this.H=null,this.l-=this.h.get(a).length,this.h.remove(a)):!1};h.Ea=function(a){cd(this);a=bd(this,a);return this.h.Ea(a)};
h.oa=function(){cd(this);for(var a=this.h.X(),b=this.h.oa(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};h.X=function(a){cd(this);var b=[];if(s(a))this.Ea(a)&&(b=Da(b,this.h.get(bd(this,a))));else{a=this.h.X();for(var c=0;c<a.length;c++)b=Da(b,a[c])}return b};h.set=function(a,b){cd(this);this.H=null;a=bd(this,a);this.Ea(a)&&(this.l-=this.h.get(a).length);this.h.set(a,[b]);this.l++;return this};
h.get=function(a,b){var c=a?this.X(a):[];return 0<c.length?String(c[0]):b};h.toString=function(){if(this.H)return this.H;if(!this.h)return"";for(var a=[],b=this.h.oa(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.X(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.H=a.join("&")};h.Wa=function(){var a=new Uc;a.H=this.H;this.h&&(a.h=this.h.Wa(),a.l=this.l);return a};
var bd=function(a,b){var c=String(b);a.G&&(c=c.toLowerCase());return c};Uc.prototype.Pb=function(a){a&&!this.G&&(cd(this),this.H=null,rc(this.h,function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<a.length&&(this.H=null,this.h.set(bd(this,d),Ea(a)),this.l+=a.length))},this));this.G=a};var fd=function(a){t(l.setImmediate)?l.setImmediate(a):(dd||(dd=ed()),dd(a))},dd,ed=function(){var a=l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d=b.location.protocol+"//"+b.location.host,a=u(function(a){if(a.origin==
d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a){var b=new a,c={},d=c;b.port1.onmessage=function(){c=c.next;var a=c.Oc;c.Oc=null;a()};return function(a){d.next={Oc:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=
null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){l.setTimeout(a,0)}};var gd=function(a){fd(function(){throw a;})},ld=function(a,b){hd||(fd(id),hd=!0);jd.push(new kd(a,b))},hd=!1,jd=[],id=function(){for(;jd.length;){var a=jd;jd=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.vd.call(c.scope)}catch(d){gd(d)}}}hd=!1},kd=function(a,b){this.vd=a;this.scope=b};var md=function(a){a.prototype.then=a.prototype.Ba;a.prototype.$goog_labs_Thenable=!0},nd=function(a){if(!a)return!1;try{return!!a.$goog_labs_Thenable}catch(b){return!1}};var qd=function(a,b){this.j=0;this.R=void 0;this.I=this.k=null;this.Za=this.Ab=!1;this.Eb=[];od(this,Error("created"));this.mc=0;try{var c=this;a.call(b,function(a){pd(c,2,a)},function(a){pd(c,3,a)})}catch(d){pd(this,3,d)}};qd.prototype.Ba=function(a,b,c){od(this,Error("then"));return rd(this,t(a)?a:null,t(b)?b:null,c)};md(qd);qd.prototype.cancel=function(a){0==this.j&&ld(function(){var b=new sd(a);td(this,b)},this)};
var td=function(a,b){if(0==a.j)if(a.k){var c=a.k;if(c.I){for(var d=0,e=-1,f=0,g;g=c.I[f];f++)if(g=g.gb)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.j&&1==d?td(c,b):(d=c.I.splice(e,1)[0],ud(c),d.Cb(b)))}}else pd(a,3,b)},wd=function(a,b){a.I&&a.I.length||2!=a.j&&3!=a.j||vd(a);a.I||(a.I=[]);a.I.push(b)},rd=function(a,b,c,d){var e={gb:null,rc:null,Cb:null};e.gb=new qd(function(a,g){e.rc=b?function(c){try{var e=b.call(d,c);a(e)}catch(r){g(r)}}:a;e.Cb=c?function(b){try{var e=c.call(d,b);!p(e)&&b instanceof
sd?g(b):a(e)}catch(r){g(r)}}:g});e.gb.k=a;wd(a,e);return e.gb};qd.prototype.yc=function(a){y(1==this.j);this.j=0;pd(this,2,a)};qd.prototype.zc=function(a){y(1==this.j);this.j=0;pd(this,3,a)};
var pd=function(a,b,c){if(0==a.j){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(nd(c)){a.j=1;c.Ba(a.yc,a.zc,a);return}if(ea(c))try{var d=c.then;if(t(d)){xd(a,c,d);return}}catch(e){b=3,c=e}}a.R=c;a.j=b;vd(a);3!=b||c instanceof sd||yd(a,c)}},xd=function(a,b,c){a.j=1;var d=!1,e=function(b){d||(d=!0,a.yc(b))},f=function(b){d||(d=!0,a.zc(b))};try{c.call(b,e,f)}catch(g){f(g)}},vd=function(a){a.Ab||(a.Ab=!0,ld(a.sd,a))};
qd.prototype.sd=function(){for(;this.I&&this.I.length;){var a=this.I;this.I=[];for(var b=0;b<a.length;b++){this.mc++;var c=a[b],d=this.R;2==this.j?c.rc(d):(ud(this),c.Cb(d))}}this.Ab=!1};
var od=function(a,b){if(b.stack){var c=b.stack.split("\n",4)[3],d=b.message,d=d+Array(11-d.length).join(" ");a.Eb.push(d+c)}},ud=function(a){for(;a&&a.Za;a=a.k)a.Za=!1},yd=function(a,b){a.Za=!0;ld(function(){if(a.Za){if(b&&b.stack&&a.Eb.length){for(var c=["Promise trace:"],d=a;d;d=d.k){for(var e=a.mc;0<=e;e--)c.push(d.Eb[e]);c.push("Value: ["+(3==d.j?"REJECTED":"FULFILLED")+"] <"+String(d.R)+">")}b.stack+="\n\n"+c.join("\n")}zd.call(null,b)}})},zd=gd,sd=function(a){x.call(this,a)};w(sd,x);
sd.prototype.name="cancel";/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var U=function(a,b){this.U=[];this.lc=a;this.gc=b||null;this.Ca=this.D=!1;this.R=void 0;this.yb=this.ic=this.xb=!1;this.Xa=0;this.k=null;this.Ua=0;this.zb=null;if(Error.captureStackTrace){var c={stack:""};Error.captureStackTrace(c,U);"string"==typeof c.stack&&(this.zb=c.stack.replace(/^[^\n]*\n/,""))}};
U.prototype.cancel=function(a){if(this.D)this.R instanceof U&&this.R.cancel();else{if(this.k){var b=this.k;delete this.k;a?b.cancel(a):(b.Ua--,0>=b.Ua&&b.cancel())}this.lc?this.lc.call(this.gc,this):this.yb=!0;this.D||this.sc(new Ad)}};U.prototype.nc=function(a,b){this.xb=!1;Bd(this,a,b)};var Bd=function(a,b,c){a.D=!0;a.R=c;a.Ca=!b;Cd(a)},Ed=function(a){if(a.D){if(!a.yb)throw new Dd;a.yb=!1}};U.prototype.v=function(a){Ed(this);Fd(a);Bd(this,!0,a)};
U.prototype.sc=function(a){Ed(this);Fd(a);Gd(this,a);Bd(this,!1,a)};var Gd=function(a,b){a.zb&&ea(b)&&b.stack&&/^[^\n]+(\n   [^\n]+)+/.test(b.stack)&&(b.stack=b.stack+"\nDEFERRED OPERATION:\n"+a.zb)},Fd=function(a){y(!(a instanceof U),"An execution sequence may not be initiated with a blocking Deferred.")},Hd=function(a,b,c,d){y(!a.ic,"Blocking Deferreds can not be re-used");a.U.push([b,c,d]);a.D&&Cd(a)};
U.prototype.Ba=function(a,b,c){var d,e,f=new qd(function(a,b){d=a;e=b});Hd(this,d,function(a){a instanceof Ad?f.cancel():e(a)});return f.Ba(a,b,c)};md(U);var Id=function(a,b){var c=u(b.ud,b);Hd(a,c,null,void 0)};U.prototype.ud=function(a){var b=new U;Hd(this,b.v,b.sc,b);a&&(b.k=this,this.Ua++);return b};
var Jd=function(a){return Ba(a.U,function(a){return t(a[1])})},Cd=function(a){if(a.Xa&&a.D&&Jd(a)){var b=a.Xa,c=Kd[b];c&&(l.clearTimeout(c.$c),delete Kd[b]);a.Xa=0}a.k&&(a.k.Ua--,delete a.k);for(var b=a.R,d=c=!1;a.U.length&&!a.xb;){var e=a.U.shift(),f=e[0],g=e[1],e=e[2];if(f=a.Ca?g:f)try{var k=f.call(e||a.gc,b);p(k)&&(a.Ca=a.Ca&&(k==b||k instanceof Error),a.R=b=k);nd(b)&&(d=!0,a.xb=!0)}catch(n){b=n,a.Ca=!0,Gd(a,b),Jd(a)||(c=!0)}}a.R=b;d&&(k=u(a.nc,a,!0),d=u(a.nc,a,!1),b instanceof U?(Hd(b,k,d),b.ic=
!0):b.Ba(k,d));c&&(c=++Ld,Kd[c]=new Md(c,b),a.Xa=c)},Dd=function(){x.call(this)};w(Dd,x);Dd.prototype.message="Deferred has already fired";Dd.prototype.name="AlreadyCalledError";var Ad=function(){x.call(this)};w(Ad,x);Ad.prototype.message="Deferred was canceled";Ad.prototype.name="CanceledError";var Md=function(a,b){this.Y=a;this.od=b;this.$c=l.setTimeout(u(this.pd,this),0)};Md.prototype.pd=function(){y(Kd[this.Y],"Cannot throw an error that is not scheduled.");delete Kd[this.Y];throw this.od;};
var Kd={},Ld=0;var Nd={1:"NativeMessagingTransport",2:"FrameElementMethodTransport",3:"IframeRelayTransport",4:"IframePollingTransport",5:"FlashTransport",6:"NixTransport",7:"DirectTransport"},Od=["pu","lru","pru","lpu","ppu"],V={},Qd=function(a){for(var b=Pd,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},Pd="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",M=Ic("goog.net.xpc");var W=function(a){this.n=a||F()};w(W,G);W.prototype.ea=0;W.prototype.e=function(){return this.n.e()};W.prototype.getName=function(){return Nd[this.ea]||""};var Sd=function(a,b){this.n=b||F();this.a=a;this.ha=new J(this);ub(this,ka(H,this.ha));this.N=new ac(100,this.e());ub(this,ka(H,this.N));this.q=new U;this.r=new U;this.o=new U;this.pb=Qd(10);this.Z=null;this.ga={};this.Qc=this.a.name;Rd(this.a,this.a.name+"_"+X(this.a));this.M=!1;Id(this.o,this.q);Id(this.o,this.r);Hd(this.o,this.Na,null,this);this.o.v(!0);this.ha.Ma(this.N,"tick",this.wa);Q("DirectTransport created. role="+X(this.a))};w(Sd,W);
var Td={},Wd=function(a){var b=new Ud(a.channelName,a.service,a.payload);a=b.wb;var c=b.Aa,b=b.ca;R("messageReceived: channel="+a+", service="+c+", payload="+b);var d=V[a];if(d)return d.J(c,b),!0;var d=Vd(b)[0],e;for(e in V){var f=V[e];if(1==X(f)&&!f.C()&&"tp"==c&&"SETUP"==d)return Rd(f,a),f.J(c,b),!0}Q("channel name mismatch; message ignored.");return!1};h=Sd.prototype;h.ea=7;
h.Va=function(a){a=Vd(a);var b=a[1];switch(a[0]){case "SETUP_ACK":this.q.D||this.q.v(!0);break;case "SETUP":this.Ya(),null!=this.Z&&this.Z!=b&&(Q("Sending SETUP and changing peer ID to: "+b),this.ya()),this.Z=b}};h.ya=function(){var a;a="SETUP,"+this.pb;this.send("tp",a)};h.Ya=function(){this.send("tp","SETUP_ACK");this.r.D||this.r.v(!0)};
h.O=function(){var a=this.e();if(a){var b=ha(a);0==(Td[b]||0)&&null==aa("crosswindowmessaging.channel",a)&&m("crosswindowmessaging.channel",Wd,a);Td[b]++;this.M=!0;this.wa()}else R("connect(): no window to initialize.")};h.wa=function(){this.a.C()?this.N.stop():(this.N.start(),this.ya())};h.send=function(a,b){if(this.a.A){var c=new Ud(this.Qc+"_"+(0==X(this.a)?1:0),a,b);this.a.b.directSyncMode?this.jc(c):this.ga[ha(c)]=bc(u(this.jc,this,c),0)}else R("send(): window not ready")};
h.jc=function(a){var b=ha(a);this.ga[b]&&delete this.ga[b];try{var c=aa("crosswindowmessaging.channel",this.a.A)}catch(d){P(M,"Can't access other window, ignoring.",d);return}if(null===c)P(M,"Peer window had no global function.");else try{c({channelName:a.wb,service:a.Aa,payload:a.ca}),Q("send(): channelName="+a.wb+" service="+a.Aa+" payload="+a.ca)}catch(e){P(M,"Error performing call, ignoring.",e)}};h.Na=function(){this.a.P(0)};
h.f=function(){if(this.M){var a=this.e(),b=ha(a);1==--Td[b]&&m("crosswindowmessaging.channel",null,a)}this.ga&&(fb(this.ga,function(a){l.clearTimeout(a)}),this.ga=null);this.q&&(this.q.cancel(),delete this.q);this.r&&(this.r.cancel(),delete this.r);this.o&&(this.o.cancel(),delete this.o);Sd.w.f.call(this)};var Vd=function(a){a=a.split(",");a[1]=a[1]||null;return a},Ud=function(a,b,c){this.wb=a;this.Aa=b;this.ca=c};var Xd=function(a,b){this.n=b||F();this.a=a;this.za=[];this.Uc=u(this.cd,this)};w(Xd,W);h=Xd.prototype;h.ea=2;h.ub=!1;h.F=0;h.O=function(){0==X(this.a)?(this.V=this.a.ia,this.V.XPC_toOuter=u(this.ec,this)):this.dc()};
h.dc=function(){var a=!0;try{this.V||(this.V=this.e().frameElement),this.V&&this.V.XPC_toOuter&&(this.sb=this.V.XPC_toOuter,this.V.XPC_toOuter.XPC_toInner=u(this.ec,this),a=!1,this.send("tp","SETUP_ACK"),this.a.P())}catch(b){O("exception caught while attempting setup: "+b)}a&&(this.hc||(this.hc=u(this.dc,this)),this.e().setTimeout(this.hc,100))};h.Va=function(a){if(0!=X(this.a)||this.a.C()||"SETUP_ACK"!=a)throw Error("Got unexpected transport message.");this.sb=this.V.XPC_toOuter.XPC_toInner;this.a.P()};
h.ec=function(a,b){this.ub||0!=this.za.length?(this.za.push({Wc:a,ca:b}),1==this.za.length&&(this.F=this.e().setTimeout(this.Uc,1))):this.a.J(a,b)};h.cd=function(){for(;this.za.length;){var a=this.za.shift();this.a.J(a.Wc,a.ca)}};h.send=function(a,b){this.ub=!0;this.sb(a,b);this.ub=!1};h.f=function(){Xd.w.f.call(this);this.V=this.sb=null};var Y=function(a,b){this.n=b||F();this.a=a;this.xa=this.a.b.ppu;this.Xc=this.a.b.lpu;this.Ta=[]},Yd,Zd;w(Y,W);h=Y.prototype;h.Rc=5;h.ea=4;h.U=0;h.la=!1;h.M=!1;h.Zb=null;var $d=function(a){return"googlexpc_"+a.a.name+"_msg"},ae=function(a){return"googlexpc_"+a.a.name+"_ack"},ce=function(a){try{if(!a.fa&&be(a.a))return a.a.A.frames||{}}catch(b){R("error retrieving peer frames")}return{}},de=function(a,b){return ce(a)[b]};
Y.prototype.O=function(){if(!this.fa&&be(this.a)){R("transport connect called");if(!this.M){R("initializing...");var a=$d(this);this.ka=ee(this,a);this.rb=this.e().frames[a];a=ae(this);this.ja=ee(this,a);this.qb=this.e().frames[a];this.M=!0}if(fe(this,$d(this))&&fe(this,ae(this)))R("foreign frames present"),this.Vb=new ge(this,de(this,$d(this)),u(this.Tc,this)),this.Ub=new ge(this,de(this,ae(this)),u(this.Sc,this)),this.Wb();else{N("foreign frames not (yet) present");if(1==X(this.a))this.Zb||0<this.Rc--||
(N("Inner peer reconnect triggered."),Rd(this.a,Qd(10)),N("switching channels: "+this.a.name),he(this),this.M=!1,this.Zb=ee(this,"googlexpc_reconnect_"+this.a.name));else if(0==X(this.a)){N("outerPeerReconnect called");for(var a=ce(this),b=a.length,c=0;c<b;c++){var d;try{a[c]&&a[c].name&&(d=a[c].name)}catch(e){}if(d){var f=d.split("_");if(3==f.length&&"googlexpc"==f[0]&&"reconnect"==f[1]){this.a.name=f[2];he(this);this.M=!1;break}}}}this.e().setTimeout(u(this.O,this),100)}}};
var ee=function(a,b){N("constructing sender frame: "+b);var c;c=document.createElement("iframe");var d=c.style;d.position="absolute";d.top="-10px";d.left="10px";d.width="1px";d.height="1px";c.id=c.name=b;c.src=a.xa+"#INITIAL";a.e().document.body.appendChild(c);return c},he=function(a){N("deconstructSenderFrames called");a.ka&&(a.ka.parentNode.removeChild(a.ka),a.ka=null,a.rb=null);a.ja&&(a.ja.parentNode.removeChild(a.ja),a.ja=null,a.qb=null)},fe=function(a,b){N("checking for receive frame: "+b);try{var c=
de(a,b);if(!c||0!=c.location.href.indexOf(a.Xc))return!1}catch(d){return!1}return!0};Y.prototype.Wb=function(){var a=ce(this);a[ae(this)]&&a[$d(this)]?(this.qc=new ie(this.xa,this.rb),this.Sa=new ie(this.xa,this.qb),R("local frames ready"),this.e().setTimeout(u(function(){this.qc.send("SETUP");this.la=!0;R("SETUP sent")},this),100)):(this.tc||(this.tc=u(this.Wb,this)),this.e().setTimeout(this.tc,100),R("local frames not (yet) present"))};
var je=function(a){if(a.vb&&a.bc){if(a.a.P(),a.na){R("delivering queued messages ("+a.na.length+")");for(var b=0,c;b<a.na.length;b++)c=a.na[b],a.a.J(c.Aa,c.ca);delete a.na}}else N("checking if connected: ack sent:"+a.vb+", ack rcvd: "+a.bc)};
Y.prototype.Tc=function(a){N("msg received: "+a);if("SETUP"==a)this.Sa&&(this.Sa.send("SETUP_ACK"),N("SETUP_ACK sent"),this.vb=!0,je(this));else if(this.a.C()||this.vb){var b=a.indexOf("|"),c=a.substring(0,b);a=a.substring(b+1);b=c.indexOf(",");if(-1==b){var d;this.Sa.send("ACK:"+c);ke(this,a)}else d=c.substring(0,b),this.Sa.send("ACK:"+d),c=c.substring(b+1).split("/"),b=parseInt(c[0],10),c=parseInt(c[1],10),1==b&&(this.Db=[]),this.Db.push(a),b==c&&(ke(this,this.Db.join("")),delete this.Db)}else P(M,
"received msg, but channel is not connected")};Y.prototype.Sc=function(a){N("ack received: "+a);"SETUP_ACK"==a?(this.la=!1,this.bc=!0,je(this)):this.a.C()?this.la?parseInt(a.split(":")[1],10)==this.U?(this.la=!1,le(this)):P(M,"got ack with wrong sequence"):P(M,"got unexpected ack"):P(M,"received ack, but channel not connected")};
var le=function(a){if(!a.la&&a.Ta.length){var b=a.Ta.shift();++a.U;a.qc.send(a.U+b);N("msg sent: "+a.U+b);a.la=!0}},ke=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),c=b.substring(c+1);a.a.C()?a.a.J(d,c):((a.na||(a.na=[])).push({Aa:d,ca:c}),N("queued delivery"))};Y.prototype.nb=3800;
Y.prototype.send=function(a,b){var c=a+":"+b;if(!A||b.length<=this.nb)this.Ta.push("|"+c);else for(var d=b.length,e=Math.ceil(d/this.nb),f=0,g=1;f<d;)this.Ta.push(","+g+"/"+e+"|"+c.substr(f,this.nb)),g++,f+=this.nb;le(this)};Y.prototype.f=function(){Y.w.f.call(this);var a=me;Ca(a,this.Vb);Ca(a,this.Ub);this.Vb=this.Ub=null;sb(this.ka);sb(this.ja);this.rb=this.qb=this.ka=this.ja=null};
var me=[],ne=u(function(){var a=me,b,c=!1;try{for(var d=0;b=a[d];d++){var e;if(!(e=c)){var f=b,g=f.pc.location.href;if(g!=f.oc){f.oc=g;var k=g.split("#")[1];k&&(k=k.substr(1),f.bd(decodeURIComponent(k)));e=!0}else e=!1}c=e}}catch(n){if(Q("receive_() failed: "+n),b=b.p.a,Q("Transport Error"),b.close(),!a.length)return}a=v();c&&(Yd=a);Zd=window.setTimeout(ne,1E3>a-Yd?10:100)},Y),oe=function(){R("starting receive-timer");Yd=v();Zd&&window.clearTimeout(Zd);Zd=window.setTimeout(ne,10)},ie=function(a,b){this.xa=
a;this.Lc=b;this.Qb=0};ie.prototype.send=function(a){this.Qb=++this.Qb%2;a=this.xa+"#"+this.Qb+encodeURIComponent(a);try{D?this.Lc.location.href=a:this.Lc.location.replace(a)}catch(b){O("sending failed",b)}oe()};var ge=function(a,b,c){this.p=a;this.pc=b;this.bd=c;this.oc=this.pc.location.href.split("#")[0]+"#INITIAL";me.push(this);oe()};var re=function(a,b){this.n=b||F();this.a=a;this.Vc=this.a.b.pru;this.ac=this.a.b.ifrid;D&&qe()};w(re,W);if(D)var se=[],te=0,qe=function(){te||(te=window.setTimeout(function(){ue()},1E3))},ue=function(a){var b=v();for(a=a||3E3;se.length&&b-se[0].timestamp>=a;){var c=se.shift().ad;sb(c);N("iframe removed")}te=window.setTimeout(ve,1E3)},ve=function(){ue()};var we={};re.prototype.ea=3;re.prototype.O=function(){this.e().xpcRelay||(this.e().xpcRelay=xe);this.send("tp","SETUP")};
var xe=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),e=b.substr(c+1);if(A&&-1!=(c=d.indexOf("|"))){var f=d.substr(0,c),d=d.substr(c+1),c=d.indexOf("+"),g=d.substr(0,c),c=parseInt(d.substr(c+1),10),k=we[g];k||(k=we[g]={Ic:[],Jc:0,Hc:0});-1!=d.indexOf("++")&&(k.Hc=c+1);k.Ic[c]=e;k.Jc++;if(k.Jc!=k.Hc)return;e=k.Ic.join("");delete we[g]}else var f=d;V[a].J(f,decodeURIComponent(e))};re.prototype.Va=function(a){"SETUP"==a?(this.send("tp","SETUP_ACK"),this.a.P()):"SETUP_ACK"==a&&this.a.P()};
re.prototype.send=function(a,b){var c=encodeURIComponent(b),d=c.length;if(A&&1800<d)for(var e=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^v()).toString(36),f=0,g=0;f<d;g++){var k=c.substr(f,1800),f=f+1800;ye(this,a,k,e+(f>=d?"++":"+")+g)}else ye(this,a,c)};
var ye=function(a,b,c,d){if(A){var e=a.e().document.createElement("div");e.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';e=e.childNodes[0];e.xpcOnload=ze}else e=a.e().document.createElement("iframe"),D?se.push({timestamp:v(),ad:e}):Lb(e,"load",ze);var f=e.style;f.visibility="hidden";f.width=e.style.height="0px";f.position="absolute";f=a.Vc;f+="#"+a.a.name;a.ac&&(f+=","+a.ac);f+="|"+b;d&&(f+="|"+d);f+=":"+c;e.src=f;a.e().document.body.appendChild(e);N("msg sent: "+f)},ze=function(){N("iframe-load");
sb(this)};re.prototype.f=function(){re.w.f.call(this);D&&ue(0)};var Z=function(a,b,c,d,e){this.n=c||F();this.a=a;this.K=e||2;y(1<=this.K);y(2>=this.K);this.Tb=b||"*";this.ha=new J(this);this.N=new ac(100,this.e());this.La=!!d;this.q=new U;this.r=new U;this.o=new U;this.pb=Qd(10);this.Z=null;this.La?1==X(this.a)?Id(this.o,this.q):Id(this.o,this.r):(Id(this.o,this.q),2==this.K&&Id(this.o,this.r));Hd(this.o,this.Na,null,this);this.o.v(!0);this.ha.Ma(this.N,"tick",this.wa);Q("NativeMessagingTransport created.  protocolVersion="+this.K+", oneSidedHandshake="+this.La+
", role="+X(this.a))};w(Z,W);Z.prototype.u=null;Z.prototype.M=!1;Z.prototype.ea=1;
var Ae={},Ce=function(a){var b=a.kb.data;if(!s(b))return!1;var c=b.indexOf("|"),d=b.indexOf(":");if(-1==c||-1==d)return!1;var e=b.substring(0,c),c=b.substring(c+1,d),b=b.substring(d+1);R("messageReceived: channel="+e+", service="+c+", payload="+b);if(d=V[e])return d.J(c,b,a.kb.origin),!0;a=Be(b)[0];for(var f in V)if(d=V[f],1==X(d)&&!d.C()&&"tp"==c&&("SETUP"==a||"SETUP_NTPV2"==a))return Rd(d,e),d.J(c,b),!0;Q('channel name mismatch; message ignored"');return!1};
Z.prototype.Va=function(a){var b=Be(a);a=b[1];switch(b[0]){case "SETUP_ACK":De(this,1);this.q.D||this.q.v(!0);break;case "SETUP_ACK_NTPV2":2==this.K&&(De(this,2),this.q.D||this.q.v(!0));break;case "SETUP":De(this,1);this.Ya(1);break;case "SETUP_NTPV2":2==this.K&&(b=this.u,De(this,2),this.Ya(2),1!=b&&null==this.Z||this.Z==a||(Q("Sending SETUP and changing peer ID to: "+a),this.ya()),this.Z=a)}};
Z.prototype.ya=function(){y(!(1==this.K&&2==this.u));if(2==this.K&&(null==this.u||2==this.u)){var a;a="SETUP_NTPV2,"+this.pb;this.send("tp",a)}null!=this.u&&1!=this.u||this.send("tp","SETUP")};Z.prototype.Ya=function(a){y(1!=this.K||2!=a,"Shouldn't try to send a v2 setup ack in v1 mode.");if(2!=this.K||null!=this.u&&2!=this.u||2!=a){if(null!=this.u&&1!=this.u||1!=a)return;this.send("tp","SETUP_ACK")}else this.send("tp","SETUP_ACK_NTPV2");this.r.D||this.r.v(!0)};
var De=function(a,b){b>a.u&&(a.u=b);1==a.u&&(a.r.D||a.La||a.r.v(!0),a.Z=null)};h=Z.prototype;h.O=function(){var a=this.e(),b=ha(a),c=Ae[b];"number"==typeof c||(c=0);0==c&&Lb(a.postMessage?a:a.document,"message",Ce,!1,Z);Ae[b]=c+1;this.M=!0;this.wa()};h.wa=function(){var a=0==X(this.a);this.La&&a||this.a.C()||this.fa?this.N.stop():(this.N.start(),this.ya())};
h.send=function(a,b){var c=this.a.A;c?(this.send=function(a,b){var f=this,g=this.a.name;this.Qa=bc(function(){f.Qa=0;try{var k=c.postMessage?c:c.document;k.postMessage?(k.postMessage(g+"|"+a+":"+b,f.Tb),R("send(): service="+a+" payload="+b+" to hostname="+f.Tb)):P(M,"Peer window had no postMessage function.")}catch(n){P(M,"Error performing postMessage, ignoring.",n)}},0)},this.send(a,b)):R("send(): window not ready")};h.Na=function(){this.a.P(1==this.K||1==this.u?200:void 0)};
h.f=function(){if(this.M){var a=this.e(),b=ha(a),c=Ae[b];Ae[b]=c-1;1==c&&Sb(a.postMessage?a:a.document,"message",Ce,!1,Z)}this.Qa&&(l.clearTimeout(this.Qa),this.Qa=0);H(this.ha);delete this.ha;H(this.N);delete this.N;this.q.cancel();delete this.q;this.r.cancel();delete this.r;this.o.cancel();delete this.o;delete this.send;Z.w.f.call(this)};var Be=function(a){a=a.split(",");a[1]=a[1]||null;return a};var Ee=function(a,b){this.n=b||F();this.a=a;this.Yb=a.at||"";this.$b=a.rat||"";var c=this.e();if(!c.nix_setup_complete)try{c.execScript("Class GCXPC____NIXVBS_wrapper\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport.GCXPC____NIXJS_handle_message(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport.GCXPC____NIXJS_create_channel(channel)\nEnd Sub\nPublic Sub GCXPC____NIXVBS_container()\n End Sub\nEnd Class\n Function GCXPC____NIXVBS_get_wrapper(transport, auth)\nDim wrap\nSet wrap = New GCXPC____NIXVBS_wrapper\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet GCXPC____NIXVBS_get_wrapper = wrap\nEnd Function",
"vbscript"),c.nix_setup_complete=!0}catch(d){O("exception caught while attempting global setup: "+d)}this.GCXPC____NIXJS_handle_message=this.Zc;this.GCXPC____NIXJS_create_channel=this.Yc};w(Ee,W);h=Ee.prototype;h.ea=6;h.ma=!1;h.aa=null;h.O=function(){0==X(this.a)?this.kc():this.fc()};
h.kc=function(){if(!this.ma){var a=this.a.ia;try{a.contentWindow.opener=(0,this.e().GCXPC____NIXVBS_get_wrapper)(this,this.Yb),this.ma=!0}catch(b){O("exception caught while attempting setup: "+b)}this.ma||this.e().setTimeout(u(this.kc,this),100)}};
h.fc=function(){if(!this.ma){try{var a=this.e().opener;if(a&&"GCXPC____NIXVBS_container"in a){this.aa=a;if(this.aa.GetAuthToken()!=this.$b){O("Invalid auth token from other party");return}this.aa.CreateChannel((0,this.e().GCXPC____NIXVBS_get_wrapper)(this,this.Yb));this.ma=!0;this.a.P()}}catch(b){O("exception caught while attempting setup: "+b);return}this.ma||this.e().setTimeout(u(this.fc,this),100)}};
h.Yc=function(a){"unknown"==typeof a&&"GCXPC____NIXVBS_container"in a||O("Invalid NIX channel given to createChannel_");this.aa=a;this.aa.GetAuthToken()!=this.$b?O("Invalid auth token from other party"):this.a.P()};h.Zc=function(a,b){this.e().setTimeout(u(function(){this.a.J(a,b)},this),1)};h.send=function(a,b){"unknown"!==typeof this.aa&&O("NIX channel not connected");this.aa.SendMessage(a,b)};h.f=function(){Ee.w.f.call(this);this.aa=null};var Ge=function(a,b){this.Pa={};for(var c=0,d;d=Od[c];c++)if(d in a&&!/^https?:\/\//.test(a[d]))throw Error("URI "+a[d]+" is invalid for field "+d);this.b=a;this.name=this.b.cn||Qd(10);this.n=b||F();this.Oa=[];this.Ra=new J(this);a.lpu=a.lpu||Oc(this.n.e().location.href)+"/robots.txt";a.ppu=a.ppu||Oc(a.pu||"")+"/robots.txt";V[this.name]=this;Ub(window,"unload",Fe)||Rb(window,"unload",Fe);Q("CrossPageChannel created: "+this.name)};w(Ge,Jc);var He=/^%*tp$/,Ie=/^%+tp$/;h=Ge.prototype;h.ba=null;h.Q=null;
h.p=null;h.j=1;h.C=function(){return 2==this.j};h.A=null;h.ia=null;
var be=function(a){try{return!!a.A&&!Boolean(a.A.closed)}catch(b){return!1}},Le=function(a){var b=document.body;Q("createPeerIframe()");var c=a.b.ifrid;c||(c=a.b.ifrid="xpcpeer"+Qd(4));var d=F(b).createElement("IFRAME");d.id=d.name=c;d.style.width=d.style.height="100%";Je(a);a.Q=new U(void 0,a);var e=Ke(a);ec(a.Ra,d,"load",a.Q.v,!1,a.Q);C||D?window.setTimeout(u(function(){b.appendChild(d);d.src=e.toString();Q("peer iframe created ("+c+")")},a),1):(d.src=e.toString(),b.appendChild(d),Q("peer iframe created ("+
c+")"))},Je=function(a){a.Q&&(a.Q.cancel(),a.Q=null);a.Oa.length=0;a.Ra.$a()},Ke=function(a){var b=a.b.pu;s(b)&&(b=a.b.pu=new S(b));var c={};c.cn=a.name;c.tp=a.b.tp;c.osh=a.b.osh;a.b.lru&&(c.pru=a.b.lru);a.b.lpu&&(c.ppu=a.b.lpu);a.b.ppu&&(c.lpu=a.b.ppu);(a=a.b.role)&&(c.role=1==a?0:1);a=b;c=ic(c);T(a);a.W.set("xpc",c);return b};h=Ge.prototype;h.O=function(a){this.Bb=a||ba;this.Q?Hd(this.Q,this.Kc,null,void 0):this.Kc()};
h.Kc=function(){Q("continueConnection_()");this.Q=null;if(this.b.ifrid){var a=this.b.ifrid;this.ia=s(a)?this.n.$.getElementById(a):a}this.ia&&((a=this.ia.contentWindow)||(a=window.frames[this.b.ifrid]),this.A=a);if(!this.A){if(window==window.top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");this.A=window.parent}if(!this.p){if(!this.b.tp){var a=this.b,b;if(t(document.postMessage)||t(window.postMessage)||A&&window.postMessage)b=1;else if(C)b=2;else if(A&&this.b.pru)b=3;
else{var c;if(c=A){c=!1;try{b=window.opener,window.opener={},c=wb(window,"opener"),window.opener=b}catch(d){}}b=c?6:4}a.tp=b}switch(this.b.tp){case 1:this.p=new Z(this,this.b.ph,this.n,!!this.b.osh,this.b.nativeProtocolVersion||2);break;case 6:this.p=new Ee(this,this.n);break;case 2:this.p=new Xd(this,this.n);break;case 3:this.p=new re(this,this.n);break;case 4:this.p=new Y(this,this.n);break;case 7:if(a=this.A)try{a=window.document.domain==this.A.document.domain}catch(e){a=!1}a?this.p=new Sd(this,
this.n):Q("DirectTransport not supported for this window, peer window in different security context or not set yet.")}if(this.p)Q("Transport created: "+this.p.getName());else throw Error("CrossPageChannel: No suitable transport found!");}for(this.p.O();0<this.Oa.length;)this.Oa.shift()()};h.close=function(){Je(this);this.j=3;H(this.p);this.Bb=this.p=null;H(this.ba);this.ba=null;Q('Channel "'+this.name+'" closed')};
h.P=function(a){this.C()||this.ba&&0!=this.ba.Y||(this.j=2,Q('Channel "'+this.name+'" connected'),H(this.ba),p(a)?(this.ba=new cc(this.Bb,a),this.ba.start()):(this.ba=null,this.Bb()))};h.Na=Ge.prototype.P;h.send=function(a,b){this.C()?be(this)?(ea(b)&&(b=ic(b)),this.p.send(Me(a),b)):(O("Peer has disappeared."),this.close()):O("Can't send. Channel not connected.")};
h.J=function(a,b,c){if(this.Q)this.Oa.push(u(this.J,this,a,b,c));else{var d=this.b.ph;if(/^[\s\xa0]*$/.test(null==c?"":String(c))||/^[\s\xa0]*$/.test(null==d?"":String(d))||c==this.b.ph)if(this.fa)P(M,"CrossPageChannel::xpcDeliver(): Disposed.");else if(a&&"tp"!=a)if(this.C()){if(a=a.replace(/%[0-9a-f]{2}/gi,decodeURIComponent),a=Ie.test(a)?a.substring(1):a,c=this.Pa[a],c||(this.Xb?c={v:ka(this.Xb,a),cc:ea(b)}:(P(this.tb,'Unknown service name "'+a+'"'),c=null)),c){var e;t:{if((d=c.cc)&&s(b))try{e=
fc(b);break t}catch(f){P(this.tb,"Expected JSON payload for "+a+', was "'+b+'"');e=null;break t}else if(!d&&!s(b)){e=ic(b);break t}e=b}null!=e&&c.v(e)}}else Q("CrossPageChannel::xpcDeliver(): Not connected.");else this.p.Va(b);else P(M,'Message received from unapproved origin "'+c+'" - rejected.')}};
var Me=function(a){He.test(a)&&(a="%"+a);return a.replace(/[%:|]/g,encodeURIComponent)},X=function(a){var b=a.b.role;return"number"==typeof b?b:window.parent==a.A?1:0},Rd=function(a,b){R("changing channel name to "+b);delete V[a.name];a.name=b;V[b]=a};Ge.prototype.f=function(){this.close();this.ia=this.A=null;delete V[this.name];H(this.Ra);delete this.Ra;Ge.w.f.call(this)};var Fe=function(){for(var a in V)H(V[a])};var Ne=function(a,b,c,d,e,f){d=new S(d||window.location.href);var g=new S;e=e?e:Math.floor(1E3*Math.random())+".talkgadget.google.com";Qc(g,e);Sc(g,"/talkgadget/d");T(g);g.W.set("token",a);f&&Rc(g,f);a=c||"wcs-iframe";c="#"+a+" { display: none; }";var k=F(void 0),n=null,r=k.$;if(A&&r.createStyleSheet)k=n=r.createStyleSheet(),A&&p(k.cssText)?k.cssText=c:k.innerHTML=c;else{r=tb(k,"head")[0];r||(n=tb(k,"body")[0],r=k.xc("head"),n.parentNode.insertBefore(r,n));var B=n=k.xc("style");A&&p(B.cssText)?B.cssText=
c:B.innerHTML=c;k.appendChild(r,n)}c={};k=new S;Qc(k,e);f&&Rc(k,f);Sc(k,"/talkgadget/xpc_blank");"http"==d.L||"https"==d.L?(Pc(g,d.L),Pc(k,d.L),f=new S,Pc(f,d.L),Qc(f,d.Da),80!=d.qa&&Rc(f,d.qa),Sc(f,b)):(Pc(g,"http"),Pc(k,"http"),f=new S("http://www.google.com/xpc_blank"));c.lpu=f.toString();c.ppu=k.toString();c.ifrid=a;c.pu=g.toString();Ge.call(this,c)};w(Ne,Ge);var $=function(a,b,c,d,e){this.readyState=0;this.Ib=[];this.onopen=b.onopen;this.onmessage=b.onmessage;this.onerror=b.onerror;this.onclose=b.onclose;this.ua=c||new Ne(a,"/_ah/channel/xpc_blank");this.wc=c?d:"wcs-iframe";this.vc=e||new Oe(a);if(!document.body)throw"document.body is not defined -- do not create socket from script in <head>.";Le(this.ua);Kc(this.ua,"onMessage",u(this.fd,this));Kc(this.ua,"onError",u(this.ed,this));Kc(this.ua,"onClosed",u(this.Ac,this));this.ua.O(u(this.dd,this))};
$.prototype.send=function(){return!1};$.prototype.close=function(){this.Ac()};$.prototype.qd=function(){for(var a=0,b;b=this.Ib[a];a++)switch(b.type){case 0:this.onopen(b.mb);break;case 1:this.onmessage(b.mb);break;case 2:this.onerror(b.mb);break;case 3:this.onclose(b.mb)}this.Ib=[]};var Pe=function(a,b,c){a.Ib.push({type:b,mb:c});window.setTimeout(u(a.qd,a),1)},Qe=function(a){return"string"==typeof a?window.JSON&&window.JSON.parse?window.JSON.parse(a):fc(a):a};
$.prototype.fd=function(a){var b=Qe(a);if(b){a=b.m;for(var b=b.s,c=this.vc,d=[],e=0,f=0;f<a.length;f++){for(var g=a.charCodeAt(f);255<g;)d[e++]=g&255,g>>=8;d[e++]=g}d.push(c.ib);c=c.gd;c.reset();c.update(d);t:if(d=c.Ga(),da(d)&&da(b)&&d.length==b.length){c=d.length;for(e=0;e<c;e++)if(d[e]!==b[e]){b=!1;break t}b=!0}else b=!1;b&&(Pe(this,1,{data:a}),this.vc.ib++)}};$.prototype.ed=function(a){(a=Qe(a))&&Pe(this,2,{description:a.d,code:a.c})};$.prototype.dd=function(){this.readyState=1;Pe(this,0,{})};
$.prototype.Ac=function(){H(this.ua);this.readyState=3;Pe(this,3,{});if(this.wc){var a=new nb,b;b=this.wc;(b=s(b)?a.$.getElementById(b):b)&&a.removeNode(b)}};
var Oe=function(a){for(;0!=a.length%4;)a+=".";this.ib=0;try{if(!Za){Za={};$a={};ab={};for(var b=0;65>b;b++)Za[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b),$a[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(b),ab[$a[b]]=b}for(var b=ab,c=[],d=0;d<a.length;){var e=b[a.charAt(d++)],f=d<a.length?b[a.charAt(d)]:0;++d;var g=d<a.length?b[a.charAt(d)]:0;++d;var k=d<a.length?b[a.charAt(d)]:0;++d;if(null==e||null==f||null==g||null==k)throw Error();
c.push(e<<2|f>>4);64!=g&&(c.push(f<<4&240|g>>2),64!=k&&c.push(g<<6&192|k))}this.Gc=c}catch(n){if(n.message)throw Error("The provided token is invalid ("+n.name+": "+n.message+")");throw Error("The provided token is invalid.");}this.B=new db;this.gd=new cb(this.B,this.Gc,this.Gc.length)};var Re=function(a){this.xd=a},Se={onopen:function(){},onclose:function(){},onerror:function(){},onmessage:function(){}};Re.prototype.open=function(a){a=a||Se;return new $(this.xd,a)};m("goog.appengine.Socket",$,void 0);m("goog.appengine.Socket.ReadyState",{CONNECTING:0,OPEN:1,Ad:2,CLOSED:3},void 0);m("goog.appengine.Socket.ReadyState.CONNECTING",0,void 0);m("goog.appengine.Socket.ReadyState.OPEN",1,void 0);m("goog.appengine.Socket.ReadyState.CLOSING",2,void 0);m("goog.appengine.Socket.ReadyState.CLOSED",3,void 0);m("goog.appengine.Socket.prototype.send",$.prototype.send,void 0);m("goog.appengine.Socket.prototype.close",$.prototype.close,void 0);m("goog.appengine.Channel",Re,void 0);
m("goog.appengine.Channel.prototype.open",Re.prototype.open,void 0);m("chat.WcsCrossPageChannel",Ne,void 0); })()
